name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.5"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        python -m spacy download en_core_web_sm
        
    - name: Generate vocabulary file
      run: |
        # Create data directory if it doesn't exist
        mkdir -p data
        # Generate a minimal vocabulary file for testing
        echo '["carnivorous", "plant", "venus", "flytrap", "pitcher", "sundew", "insect", "trap", "leaf", "grow", "nutrient", "soil"]' > data/test_vocabulary.json
        # Set the VOCABULARY_PATH environment variable
        echo "VOCABULARY_PATH=data/test_vocabulary.json" >> $GITHUB_ENV
        # Verify the file was created
        ls -la data/
    
    - name: Run tests with pytest
      run: |
        python -m pytest --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: false  # Optional: set to true if you want to fail on coverage issues
